# Generated by Django 6.0 on 2026-01-04 11:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Rich text description of the incident')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('new', 'New'), ('investigating', 'Investigating'), ('analyzing', 'Analyzing'), ('root_cause_found', 'Root Cause Found'), ('mitigating', 'Mitigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('database', 'Database'), ('network', 'Network'), ('application', 'Application'), ('infrastructure', 'Infrastructure'), ('security', 'Security'), ('other', 'Other')], max_length=20)),
                ('affected_services', models.JSONField(default=list, help_text='List of affected services/components')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_resolution_time', models.DurationField(blank=True, null=True)),
                ('actual_resolution_time', models.DurationField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='For planned maintenance', null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='companies.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline', models.TextField(blank=True, help_text='Generated timeline from logs')),
                ('root_cause', models.TextField(blank=True, help_text='Identified root cause')),
                ('explanation', models.TextField(blank=True, help_text='Detailed explanation')),
                ('mitigation_steps', models.TextField(blank=True, help_text='Suggested mitigation steps (JSON or text)')),
                ('confidence_score', models.FloatField(default=0.0, help_text='Confidence score 0-1')),
                ('category', models.CharField(blank=True, help_text='Auto-detected category', max_length=20)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='incidents.incident')),
            ],
            options={
                'verbose_name_plural': 'Incident Analyses',
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('attachments', models.JSONField(default=list, help_text='List of attachment file paths')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='incidents.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='incident_logs/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='File extension or type', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_content', models.TextField(blank=True, help_text='Processed/extracted log content')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='incidents.incident')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('assigned', 'Assigned'), ('status_changed', 'Status Changed'), ('commented', 'Commented'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], max_length=20)),
                ('from_state', models.CharField(blank=True, max_length=20)),
                ('to_state', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='incidents.incident')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('incident_created', 'Incident Created'), ('incident_assigned', 'Incident Assigned'), ('incident_updated', 'Incident Updated'), ('incident_resolved', 'Incident Resolved'), ('comment_added', 'Comment Added'), ('status_changed', 'Status Changed')], max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.incident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimilarIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='Cosine similarity score 0-1')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_incidents', to='incidents.incident')),
                ('similar_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='incidents.incident')),
            ],
            options={
                'ordering': ['-similarity_score'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['company', 'status'], name='incidents_i_company_caa603_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['company', 'severity'], name='incidents_i_company_048421_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['company', 'created_at'], name='incidents_i_company_14dc95_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'severity'], name='incidents_i_status_85e429_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read'], name='incidents_n_user_id_9cb976_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='incidents_n_user_id_199e6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='similarincident',
            unique_together={('incident', 'similar_to')},
        ),
    ]
