# Generated by Django 6.0 on 2026-01-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentanalysis',
            name='fix_steps',
            field=models.JSONField(blank=True, default=list, help_text='Structured remediation steps'),
        ),
    ]
