# Generated by Django 6.0 on 2026-01-29 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_alter_incidentanalysis_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='incidents.incident')),
            ],
        ),
    ]
