# Generated by Django 6.0 on 2026-01-31 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_incidentembedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentanalysis',
            name='postmortem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='affected_services',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='incidentanalysis',
            name='ai_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='incidentcomment',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
